### ISSUE TITLE
Không gõ được trên app Sticky Notes trên Windows 10

### ISSUE THREAD

**Issue by zenfas** [dinhngtu/VietType#6]
Trên Windows 10, không thể gõ tiếng Việt trên app Sticky Noted

**Comment by dinhngtu** [comment]
![image](https://user-images.githubusercontent.com/1257909/194899608-5a68bbb7-cd5a-4d07-955a-d01a05633fff.png)

**Comment by zenfas** [comment]
Lỗi xảy ra khi mình turn on tính năng "Show text suggestions as I type" trong Settings => Devices => Typing.
Nếu bật tính năng này nhiều app hỗ trợ tiên đoán như Word, Firefox, Sticky Notes...sẽ không gõ tiếng Việt được, giống như nó bị VietType hiểu là đang gõ tiếng Anh dùng mình đang tích chọn tiếng Việt, nhưng nếu mình dùng bàn phím Telex hoặc VNI của Windows hoặc Unikey thì vẫn gõ bình thường.

**Comment by zenfas** [comment]
Ngoài ra, phần Setting của app, bạn xem gom lại 1 hiển thị duy nhất trong Menu start để nhìn gọn hơn được không?

**Comment by dinhngtu** [comment]
Fixed: https://github.com/dinhngtu/VietType/releases/tag/1.7.7

> Ngoài ra, phần Setting của app, bạn xem gom lại 1 hiển thị duy nhất trong Menu start để nhìn gọn hơn được không?

Tôi có thể sẽ hợp nhất shortcut Enable/Disable vào app Settings sau.
