### ISSUE TITLE
Lỗi hiển thị chữ NGƯỜI trong Excel của bản Office 365

### ISSUE THREAD

**Issue by zenfas** [dinhngtu/VietType#7]
Nếu gõ chứ "NGƯỜI" thì chữ Ư sẽ bị nhỏ lại bất thường, Unikey không bị (font Calibri hoặc Times New Roman)

**Comment by dinhngtu** [comment]
Cảm ơn bạn đã report. Đã sửa trong [release 1.7.5](https://github.com/dinhngtu/VietType/releases/tag/1.7.5) (fafbfd7)
